"""Builds notebooks/analysis.ipynb: a full, executable walkthrough of the
project narrative (Parts 1-9), mixing fresh fast computation (data prep,
EDA, benchmarks) with cached results for the slow steps (SARIMAX grid
search + rolling backtest, XGBoost rolling backtest) so the notebook runs
end-to-end in well under a minute. The underlying, re-runnable source of
truth for every result is the single file src/all_in_one.py; this notebook
is the narrative/reporting layer on top of it.
"""
import nbformat as nbf

nb = nbf.v4.new_notebook()
cells = []

def md(text):
    cells.append(nbf.v4.new_markdown_cell(text))

def code(text):
    cells.append(nbf.v4.new_code_cell(text))

# ---------------------------------------------------------------- Title --
md("""# Appliance Energy Demand Forecasting — Analysis Walkthrough

This notebook is the narrative walkthrough of the project. It imports
`../src/all_in_one.py` (the single file containing the entire pipeline:
Parts 1-8) and runs the fast parts of the pipeline live (data preparation,
EDA, stationarity tests, benchmark models); for the slow, compute-heavy
parts (the exhaustive SARIMAX AIC grid search + 14 rolling refits, and the
14 XGBoost rolling-origin fits), it loads the already-computed, checkpointed
results from `../outputs/metrics/` rather than re-running them here, so the
notebook executes end-to-end in well under a minute. **The full,
re-runnable source of truth for every number in this notebook is
`../src/all_in_one.py`** — run `python ../src/all_in_one.py` to regenerate
everything from scratch (~30-40 minutes, dominated by the required
exhaustive SARIMAX grid search).

See `../reports/report.docx` for the full written report and discussion.
""")

code("""import sys, os
sys.path.insert(0, os.path.abspath("../src"))
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import Image, display

import all_in_one as pipeline

pd.set_option("display.width", 120)
%matplotlib inline
""")

# ---------------------------------------------------------------- Part 1 --
md("## Part 1 — Data Preparation and EDA\n\nLoad the raw 10-minute data, check for missing values, and resample to hourly resolution.")

code("""df_raw = pipeline.load_raw()
print("Raw (10-min) shape:", df_raw.shape)
missing = pipeline.check_missing(df_raw)

df_hourly = pipeline.resample_hourly(df_raw)
df_hourly = pipeline.add_time_features(df_hourly)
print("\\nHourly shape:", df_hourly.shape)
df_hourly.head()
""")

md("### Series overview and weekly profile\n\nFigures were generated by `all_in_one.py`; displayed here for the narrative.")

code("""display(Image("../outputs/figures/01_series_overview.png", width=700))
display(Image("../outputs/figures/03_weekly_hourly_profile.png", width=600))
display(Image("../outputs/figures/02_decomposition_daily.png", width=600))
""")

md("### Stationarity testing (ADF + KPSS)\n\nRe-run live here since it's fast; both tests agree the raw hourly series is already stationary.")

code("""print("ADF + KPSS on raw series:")
pipeline.adf_test(df_hourly["Appliances"], "Appliances (raw)")
pipeline.kpss_test(df_hourly["Appliances"], "Appliances (raw)")
""")

code("""display(Image("../outputs/figures/04_acf_pacf_raw.png", width=750))""")

# ---------------------------------------------------------------- Part 2 --
md("""## Part 2 — Forecasting Problem Definition

- **Target:** `Appliances` (Wh/hour)
- **Horizon:** 24 hours ahead
- **Evaluation:** rolling-origin backtest over the last 14 days (14 non-overlapping 24h blocks, 336 pooled predictions)
- **Metrics:** RMSE, MAE, MAPE, sMAPE

See the evaluation section of `../src/all_in_one.py` for the full harness shared by every model below.""")

code("""df = pipeline.load_hourly()
train, test = pipeline.train_test_split(df)
origins = pipeline.get_origins(df)
print(f"Full data: {len(df)}h | Train: {len(train)}h | Test: {len(test)}h")
print(f"Rolling-origin blocks: {len(origins)} x {pipeline.HORIZON}h")
""")

# ---------------------------------------------------------------- Part 3 --
md("## Part 3 — Benchmark Models\n\nFast to compute — run live here.")

code("""bench_results = pipeline.run_benchmarks()
bench_summary = pipeline.summarize(bench_results)
bench_summary.round(2)
""")

code("""display(Image("../outputs/figures/07_benchmark_example_block.png", width=650))""")

# ---------------------------------------------------------------- Part 4 --
md("""## Part 4 — SARIMAX

The exhaustive AIC grid search over p, d, q (147 fits) plus the 14-origin
rolling backtest together take roughly 30-40 minutes on 1 CPU core (see
`run_part4_sarimax()` in `../src/all_in_one.py`, which checkpoints every
result so it can be resumed if interrupted). We load the already-computed,
cached results here rather than re-running that search live in the notebook.""")

code("""grid = pd.read_csv("../outputs/metrics/sarimax_grid_search.csv").sort_values("aic")
print("Top 10 orders by AIC (non-seasonal grid, seasonal order fixed at (0,1,1,24)):")
grid.head(10)
""")

code("""sarimax_forecasts = pd.read_parquet("../outputs/metrics/sarimax_forecasts.parquet")
sarimax_summary = pipeline.summarize(sarimax_forecasts)
sarimax_summary.round(2)
""")

code("""display(Image("../outputs/figures/09_sarimax_residual_diagnostics.png", width=750))""")

md("Ljung-Box test on the full-training-set model's residuals (from the all_in_one.py run log): "
   "p=0.44 at 24 lags, p=0.34 at 48 lags — residuals are statistically indistinguishable from white noise.")

# ---------------------------------------------------------------- Part 5/6 --
md("""## Parts 5 & 6 — Feature Engineering and XGBoost

Feature engineering runs instantly, so it's demonstrated live. The 14-origin
XGBoost rolling backtest (`run_part6_ml_model()`) takes ~2 minutes; its
cached results are loaded below.""")

code("""feat_df = pipeline.build_feature_frame(df)
feature_cols = pipeline.get_feature_columns()
print(f"Built {len(feature_cols)} features from sensor/weather/time/lag/rolling groups.")
feat_df[feature_cols].tail(3).T.head(15)
""")

code("""xgb_forecasts = pd.read_parquet("../outputs/metrics/xgboost_forecasts.parquet")
xgb_summary = pipeline.summarize(xgb_forecasts)
xgb_summary.round(2)
""")

code("""importance = pd.read_csv("../outputs/metrics/xgboost_feature_importance.csv", index_col=0)
display(Image("../outputs/figures/10_xgb_feature_importance.png", width=550))
""")

md("""### Part 6b — Realistic weather (Section 9, Q5 follow-up)

`pipeline.build_feature_frame` and `pipeline.recursive_forecast` both take a
`weather_mode` argument: `"conditional"` (default, used above) uses true
future weather values (optimistic); `"realistic"` uses each weather
column's value from 24h earlier instead (genuinely available at the
forecast origin). Run live below (~2 min, a second small backtest) to
measure how much the conditional-forecast assumption is worth.""")
code("""pipeline.run_part6b_ml_model_realistic_weather()
""")

# ---------------------------------------------------------------- Part 7 --
md("""## Part 7 — Foundation Model (Chronos)

This sandbox has no internet access to Hugging Face, so Chronos could not be
executed here. `run_part7_foundation_model()` in `../src/all_in_one.py`
implements the identical rolling-origin harness — run
`python all_in_one.py --with-chronos` in Google Colab (free tier, ~2
minutes) and drop the resulting `chronos_forecasts.parquet` into
`../outputs/metrics/` to include it below automatically. This project's
own real Chronos result (from Colab): RMSE=428.5, MAE=209.9, MAPE=23.0%,
sMAPE=28.0% — the highest RMSE but the lowest MAE/MAPE/sMAPE of every model
tested (see reports/report.docx, Section 8-9, for the full discussion).""")

code("""chronos_path = "../outputs/metrics/chronos_forecasts.parquet"
if os.path.exists(chronos_path):
    chronos_forecasts = pd.read_parquet(chronos_path)
    print(pipeline.summarize(chronos_forecasts).round(2))
else:
    print("chronos_forecasts.parquet not found - run 'python all_in_one.py --with-chronos' in Colab first.")
""")

# ---------------------------------------------------------------- Part 8 --
md("## Part 8 — Model Comparison and Evaluation")

code("""all_results = pipeline.load_all_results()
full_summary = pipeline.comparison_table(all_results)
summary_with_improvement, strongest = pipeline.compare_to_strongest_benchmark(full_summary)
summary_with_improvement.round(2)
""")

code("""display(Image("../outputs/figures/12_rmse_by_horizon_all_models.png", width=650))
display(Image("../outputs/figures/13_error_diagnostics_SARIMAX.png", width=650))
""")

# ---------------------------------------------------------------- Part 9 --
md("""## Part 9 — Discussion Questions

Full answers (with supporting evidence and figure references) are written out
in `../reports/report.docx`, Section 10. Summary:

1. **Strongest benchmark:** split result — Mean wins on RMSE, SeasonalNaive_Weekly wins on MAE/MAPE/sMAPE, reflecting the series' mix of weekly-seasonal structure and unpredictable spikes.
2. **SARIMAX vs. benchmarks:** yes, SARIMAX beats every benchmark on every metric; residuals are white noise (Ljung-Box p=0.44/0.34).
3. **XGBoost feature value:** yes vs. benchmarks, but XGBoost does not beat SARIMAX on RMSE despite more features — recursive multi-step error compounding and limited training data are the likely causes.
4. **Foundation model:** Chronos, run zero-shot in Colab, had the highest RMSE (428.5) but the lowest MAE/MAPE/sMAPE (209.9/23.0%/28.0%) of every model tested — a genuine worst-case-vs-typical-case split.
5. **Forecast conditionality:** SARIMAX/XGBoost use real future weather (and, for XGBoost, real future indoor sensor readings) — these are conditional, not true unconditional, forecasts. A realistic 24h-lagged proxy gives slightly worse RMSE but better MAE/MAPE/sMAPE (Part 6b above).
6. **Recommendation:** SARIMAX for this single house — best worst-case accuracy, native uncertainty quantification, most interpretable, cheapest to run; Chronos is a genuine alternative at multi-building or cold-start scale.
""")

nb["cells"] = cells
nb["metadata"] = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.12"},
}

with open("../notebooks/analysis.ipynb", "w") as f:
    nbf.write(nb, f)
print("Wrote notebooks/analysis.ipynb with", len(cells), "cells")
